"""
Ecosystem Service Extraction System for Sustainable Building Case Studies
Extracts ecosystem services evidenced in the case study research of a paper
"""

import re
import json
import logging
from pathlib import Path
from typing import Dict, List, Optional

# ── Few-shot example directory (relative to this file) ──────────────────────
_EXAMPLES_DIR = Path(__file__).resolve().parent.parent / "test_papers" / "examples"

logger = logging.getLogger(__name__)

output_dir = Path("/app/test_papers/preprocessed")

class EcosystemServicePromptBuilder:
    """Builds targeted prompts for extracting ecosystem services"""

    # ── Few-shot example helpers ─────────────────────────────────────────

    @staticmethod
    def _load_all_ecosystem_service_examples() -> List[dict]:
        """Load all section-skeleton few-shot examples for ecosystem service extraction.
        Globs for ecosystem_service_extraction_example_*.json in the examples directory.
        Returns an empty list if no files are found so the prompt still works."""
        pattern = "ecosystem_service_extraction_example_*.json"
        example_paths = sorted(_EXAMPLES_DIR.glob(pattern))
        if not example_paths:
            logger.warning(f"No few-shot examples matching {pattern} in {_EXAMPLES_DIR} — skipping.")
            return []
        examples = []
        for path in example_paths:
            try:
                with open(path, "r", encoding="utf-8") as f:
                    examples.append(json.load(f))
                    logger.info(f"Loaded few-shot example: {path.name}")
            except Exception as e:
                logger.warning(f"Failed to load few-shot example {path.name}: {e} — skipping.")
        return examples

    @staticmethod
    def _format_example_block(example: dict, index: int = 1, total: int = 1) -> str:
        """Format the loaded example dict into a prompt-ready text block."""
        skeleton = example.get("section_skeleton", "")
        expected = json.dumps(example.get("expected_output", {}), indent=2)
        lesson = example.get("lesson", "")
        citation = example.get("citation", f"Example {index}")

        return (
            f"\n--- FEW-SHOT EXAMPLE {index} of {total} (DIFFERENT PAPER — DO NOT COPY): {citation} ---\n"
            f"{skeleton}\n\n"
            f"Correct extraction from the example paper above (NOT your task):\n{expected}\n\n"
            f"KEY LESSON: {lesson}\n"
            f"--- END OF EXAMPLE {index} — THE ABOVE IS NOT THE PAPER YOU SHOULD EXTRACT FROM ---\n"
        )

    # ── Main prompt builder ──────────────────────────────────────────────

    @staticmethod
    def build_ecosystem_service_extraction_prompt(text: str, file_name: str = "") -> str:
        """Build prompt for extracting ecosystem services from case study"""

        base_name = Path(file_name).stem

        # Optionally inject few-shot examples
        examples = EcosystemServicePromptBuilder._load_all_ecosystem_service_examples()
        if examples:
            example_blocks = "\n".join(
                EcosystemServicePromptBuilder._format_example_block(ex, i + 1, len(examples))
                for i, ex in enumerate(examples)
            )
        else:
            example_blocks = ""

        current_prompt = f"""{example_blocks}
        
The examples above demonstrate the EXTRACTION PROCESS only. The content in them should NOT be used or repeated — extract only from the paper provided below. 

Paper text:
{text}

---
You are an expert in ecosystem services analysis and sustainable building research.

Your task: Extract ALL ecosystem services that are EVIDENCED or PROVIDED by the case study / research project described in this paper.

Ecosystem services are the benefits that humans and all living organisms derive, either directly or indirectly from the functions of ecosystems.
ESs are categorized in regulation and maintenance services as well as provisioning services and cultural services. 
The regulation and maintenance services represent ecological processes such as nutrient cycling and regulation of soil, water and air quality. 
Provisioning services are the material benefits that are generated by ecological processes (e.g. food, fresh water, and energy), 
while the cultural services are immaterial benefits that result from the ecosystems (e.g. relaxation and well-being). 

Equivalent terms that also refer to ecosystem services are:
- ecological benefit
- ecological value
- ecological performance
- environmental value
- social value
- social benefit
- health benefit

Ecosystem services are often the dependent variables in the study. They are the outcome of the study, achieved through the implementation of design strategies.

LOOK FOR PHRASES LIKE:
- "for this study" 
- "for this research" 
- "Results"
- "Discussion"

IGNORE PHRASES LIKE:
- "previous studies"
- Literature review sections

For EACH ecosystem service found, provide:
1. name: The ecosystem service name (use EXACTLY one of the names from the taxonomy above)
2. anchor: A SHORT EXACT PHRASE of 5-10 words copied verbatim from the paper that
   best locates where this ecosystem service is discussed. This phrase will be searched in the
   source document to retrieve the surrounding passage — it must exist exactly as
   written in the paper text above.
   RULES FOR ANCHOR:
   - Copy 5-10 consecutive words exactly as they appear in the paper text above
   - Choose words that are specific and unique to this ecosystem service mention
   - Do NOT paraphrase, summarise, or change any words
   - If you cannot identify a specific passage in the text above, set anchor to null rather than guessing

Reply with a SINGLE JSON object only. No preamble, no conversational filler.

The JSON object MUST follow this structure:
{{
    "ecosystem_services": [
        {{
            "name": "ecosystem service name from taxonomy",
            "anchor": "five to ten exact words from the paper",
        }},
        {{
            "name": "another ecosystem service name from taxonomy",
            "anchor": null,
        }}
    ]
}}

CRITICAL RULES:
- Extract ONLY ecosystem services evidenced in THIS paper's OWN case study, experiment, or research
- Do NOT extract services cited from other literature, reviews, or background references
- Focus on sections like "Case Study", "Methods", "Results", "Discussion" — 
- IGNORE "Literature Review" and references sections
- The anchor must be a verbatim copy of words from the paper text above — do not
  invent or paraphrase
- If you cannot find a passage in the text that evidences a service, set
  anchor to null rather than guessing
- Use the EXACT service name from the taxonomy provided above
- Include the correct category for each service
- If no ecosystem services are found, return {{"ecosystem_services": []}}

JSON output (values must come ONLY from the paper text above):"""
        # Save prompt text
        # prompt_path = output_dir / f"{base_name}_ecosystem_service_extraction_prompt.txt"
        # with open(prompt_path, 'w', encoding='utf-8') as f:
        #     f.write(current_prompt)
        # logger.info(f"  ✓ Saved prompt text: {prompt_path}")

        return current_prompt


class EcosystemServiceExtractor:
    """Main ecosystem service extraction orchestrator"""

    def __init__(self, model: str = "llama3.2", base_url: str = "http://localhost:11434"):
        self.prompt_builder = EcosystemServicePromptBuilder()
        self.model = model
        self.base_url = base_url

    def _query_ollama(self, prompt: str) -> str:
        """Send query to Ollama API and return response"""
        try:
            import requests

            response = requests.post(
                f"{self.base_url}/api/generate",
                json={
                    "model": self.model,
                    "prompt": prompt,
                    "stream": False,
                    "options": {
                        "temperature": 0.2,  # Slightly higher to allow for matching services to the taxonomy
                        "num_predict": 3000,
                        "num_ctx": 12000,    # Prevent prompt truncation
                    }
                },
                timeout=240  # Longer timeout due to large taxonomy in prompt
            )

            if response.status_code == 200:
                return response.json().get('response', '')
            else:
                logger.error(f"API returned status {response.status_code}")
                return '{}'

        except Exception as e:
            logger.error(f"Error querying Ollama: {e}")
            return '{}'

    def _extract_json(self, response: str) -> dict:
        """Extract and parse JSON from LLM response"""
        # Remove markdown code blocks if present
        response = re.sub(r'```json\s*', '', response)
        response = re.sub(r'```\s*', '', response)

        # Try to find JSON in response
        json_match = re.search(r'\{.*\}', response, re.DOTALL)
        if json_match:
            try:
                return json.loads(json_match.group())
            except json.JSONDecodeError as e:
                logger.error(f"JSON parse error: {e}")
                logger.debug(f"Failed to parse: {json_match.group()[:500]}")

        return {'ecosystem_services': []}

    def extract_from_text(self, text: str, verbose: bool = True, file_name: str = "") -> Dict:
        """
        Extract ecosystem services from a research paper text.

        Returns raw LLM output with 'anchor' fields. Call
        resolve_ecosystem_service_contexts() from context_resolver.py afterwards
        to replace anchors with verified context passages.

        Args:
            text: Full text of the research paper
            verbose: Print progress information

        Returns:
            Dictionary containing list of ecosystem services (with anchor fields,
            not yet resolved to context passages)
        """
        if verbose:
            logger.info("Extracting ecosystem services from text...")

        # Build and send prompt
        prompt = self.prompt_builder.build_ecosystem_service_extraction_prompt(text, file_name)
        response = self._query_ollama(prompt)

        if verbose and not response:
            logger.warning("Empty response from Ollama")

        # Extract JSON
        raw_results = self._extract_json(response)

        # Debug output
        if not raw_results.get('ecosystem_services') and verbose:
            logger.debug(f"Raw LLM response: {response[:300]}...")

        services = raw_results.get('ecosystem_services', [])

        if verbose:
            logger.info(f"Found {len(services)} ecosystem services")
            for service in services[:5]:
                name = service.get("name", "Unnamed")
                category = service.get("category", "Unknown")
                confidence = service.get("confidence", "N/A")
                anchor = service.get("anchor")
                anchor_display = f'"{anchor[:40]}..."' if anchor else "null"
                logger.info(
                    f"  - {name} [{category}] (confidence: {confidence}) | anchor: {anchor_display}"
                )

        return {'ecosystem_services': services}

    def extract_from_file(self, filepath: str, verbose: bool = True) -> Dict:
        """
        Extract ecosystem services from a text file

        Note: for anchor resolution you will need the same text string — either
        re-read the file or pass raw_text directly to extract_from_text().
        """
        with open(filepath, 'r', encoding='utf-8') as f:
            text = f.read()

        return self.extract_from_text(text, verbose)

    def save_results(self, results: Dict, output_path: str):
        """Save extraction results to JSON file"""
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(results, f, indent=2, ensure_ascii=False)

    def generate_report(self, results: Dict) -> str:
        """Generate a human-readable report from results"""
        report_lines = []

        report_lines.append("=" * 80)
        report_lines.append("ECOSYSTEM SERVICE EXTRACTION REPORT")
        report_lines.append("=" * 80)

        services = results.get('ecosystem_services', [])

        if not services:
            report_lines.append("\n  No ecosystem services identified.")
        else:
            report_lines.append(f"\nTotal ecosystem services found: {len(services)}\n")

            # Group by category for readability
            by_category: Dict[str, list] = {}
            for service in services:
                cat = service.get('category', 'Unknown')
                by_category.setdefault(cat, []).append(service)

            for category, cat_services in by_category.items():
                report_lines.append(f"\n--- {category.upper()} SERVICES ({len(cat_services)}) ---")

                for i, service in enumerate(cat_services, 1):
                    name = service.get("name", "Unnamed Service")
                    confidence = service.get("confidence", "N/A")
                    context = service.get("context")           # resolved passage (str|None)
                    anchor_text = service.get("anchor_text")  # original LLM anchor
                    verified = service.get("anchor_verified")
                    score = service.get("anchor_match_score")

                    report_lines.append(f"\n  Service {i}: {name}")
                    report_lines.append(f"  Confidence: {confidence}")

                    if verified is not None:
                        status = "✓ verified" if verified else "✗ UNVERIFIED"
                        score_str = f" (match score: {score:.2f})" if score is not None else ""
                        report_lines.append(f"  Anchor: {status}{score_str}")
                        if anchor_text:
                            report_lines.append(f'  Anchor text: "{anchor_text}"')

                    if context:
                        report_lines.append(f"\n  Context passage:")
                        report_lines.append(f'    "{context}"')
                    else:
                        report_lines.append("\n  Context passage: not retrieved")

                    report_lines.append("")

        report_lines.append("=" * 80)
        return "\n".join(report_lines)


def main():
    """Example usage"""
    import sys

    if len(sys.argv) < 2:
        print("Usage: python ecosystem_service_extractor.py <input_text_file> [output_json_file]")
        print("\nExample:")
        print("  python ecosystem_service_extractor.py paper.txt ecosystem_services.json")
        sys.exit(1)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(levelname)s - %(message)s",
    )

    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "ecosystem_services.json"

    print(f"Processing: {input_file}")
    print(f"Output will be saved to: {output_file}\n")

    with open(input_file, "r", encoding="utf-8") as f:
        raw_text = f.read()

    extractor = EcosystemServiceExtractor(model="llama3.2")

    # Step 1: extract (produces anchors)
    results = extractor.extract_from_text(raw_text, verbose=True)

    # Step 2: resolve anchors → real context passages
    from context_resolver import resolve_ecosystem_service_contexts
    results = resolve_ecosystem_service_contexts(results, raw_text)

    extractor.save_results(results, output_file)
    print(f"\n✓ Results saved to {output_file}")

    report = extractor.generate_report(results)
    print("\n" + report)

    report_file = output_file.replace(".json", "_report.txt")
    with open(report_file, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"✓ Report saved to {report_file}")


if __name__ == "__main__":
    main()